apiVersion: apps/v1
kind: Deployment
metadata:
  name: srijan2002
  labels:
    app: srijan2002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srijan2002
  template:
    metadata:
      labels:
        app: srijan2002
    spec:
      containers:
        - name: srijan2002
          image: 603631440954.dkr.ecr.us-east-1.amazonaws.com/srijan2002:srijan2002
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
